### PR TITLE
heat pipe support

### PR DESCRIPTION
**Pull request by misterbigstuff**
read temp directly from heat pipe so it doesn't need to be next to reactor.

### CODE REVIEW

**Comment by Yousei9** [comment]
Who cares for heat pipe temp?
The important entities are reactor and heat exchanger, both already covered.

**Comment by misterbigstuff** [comment]
Space Exploration users.

**Comment by Yousei9** [comment]
I'm not using that mod.
How is reading temp from pipes useful there?

**Comment by misterbigstuff** [comment]
there's space ships that use reactors, and the floor space is extremely limited - the spaceship won't take off, it'll fall apart or whatnot, if you exceed the structural integrity.. having it next to reactor/HE is less flexible than having it at the end of a heat pipe.

**Comment by misterbigstuff** [comment]
image

**Comment by Yousei9** [comment]
Read temp from the furthest heat exchanger and as bonus you get water and steam levels.

**Comment by misterbigstuff** [comment]
i don't see what the problem is with merging the request, your license doesn't allow forks. shall I just fork it anyway?

**Comment by misterbigstuff** [comment]
SE has planned additions that use no HE or Reactor, but still have heat buffers with temperature. so your proposed solution is not as good as merging this change.

**Comment by Yousei9** [comment]
> 
> 
> i don't see what the problem is with merging the request, your license doesn't allow forks. shall I just fork it anyway?

Correct, releasing a fork is forbidden.
Are you trying to threaten a release in case I don't merge that pull request? If so this conversation is over.

**Comment by misterbigstuff** [comment]
yep that's exactly what I'm "threatening", to "steal" your code and publish it with the modifications. thanks.

**Comment by misterbigstuff** [comment]
(though, in all seriousness, no, i was asking for your stupid permission, like the license states is required.)

**Comment by Yousei9** [comment]
You don't ask for permission with "either give me what I want or I'll do it myself".
So my answer is no.

**Comment by misterbigstuff** [comment]
merging a pull request would have been easier than being a lil bitch about it.

**Comment by Yousei9** [comment]
Telling me why you want that without being an entitled ass or insulting me would have gotten you what you want.

**Comment by misterbigstuff** [comment]
image
jfyi the reason Factorio isn't open source is because Wube has violated licenses of libraries, lol

**Comment by misterbigstuff** [comment]
entitled assholes demand you to implement a change and don't go through the EFFORT of submitting a PR to make *your* mod better, with *your* name on the submitted improvements - not mine.

**Pull request closed without merging**
